version: "3.8"
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  mongo_data_volume:

services:
  db:
    image: mongo
    networks:
      - backend
    volumes:
      - mongo_data_volume:/data/db

  vote:
    build:
      context: .
    networks:
      - backend
      - frontend
    environment:
      - MONGO_URI=mongodb://db:27017
      - MONGO_DATABASE=votes_prod
    depends_on:
      - "db"

  front:
    image: nginx
    networks:
      - frontend
    ports:
      - "$FRONT_PORT:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "vote"