pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '/opt/apache-maven-3.8.3/bin/mvn -B -DskipTests clean package'
            }
        }
        stage('Start service') {
            steps {
                sh 'sh ./scripts/start-service-docker.sh'
            }
        }
//         stage('Test') {
//             steps {
//                 sh '/opt/apache-maven-3.8.3/bin/mvn test'
//             }
//         }
//         stage('Deliver') {
//             steps {
//                 sh 'scripts/deliver-docker.sh'
//             }
//         }
    }
}